export const mockMovie = {
  id: "1",
  title: "Эхо Снов",
  originalTitle: "Echo of Dreams",
  year: 2024,
  director: "Алексей Сюрреалист",
  genres: ["Артхаус", "Фантастика", "Драма"],
  synopsis: "В мире, где сны можно записывать на пленку, один архивариус находит кассету, которая меняет реальность того, кто её просматривает. Визуальный шедевр о границах памяти и обещаниях, данных самим себе.",
  posterColor: "from-twinpy-purple to-twinpy-neon",
  rating: 8.7,
};

export const mockMovies = [
  mockMovie,
  {
    id: "2",
    title: "Пурпурный Час",
    originalTitle: "The Purple Hour",
    year: 2023,
    director: "Мария Неонова",
    genres: ["Триллер", "Артхаус"],
    synopsis: "Каждую ночь в 3:33 город окрашивается в пурпурный, и только один человек видит, что скрывается за этим цветом. Медитативный триллер о страхе и принятии.",
    posterColor: "from-twinpy-neon to-twinpy-gold",
    rating: 7.9,
  },
  {
    id: "3",
    title: "Тихий Океан Памяти",
    originalTitle: "Silent Ocean of Memory",
    year: 2024,
    director: "Дмитрий Волна",
    genres: ["Драма", "Мелодрама"],
    synopsis: "Два незнакомца встречаются на пустынном берегу и обнаруживают, что их воспоминания переплетены. История о связи, которую невозможно разорвать.",
    posterColor: "from-twinpy-turquoise to-twinpy-purple",
    rating: 9.1,
  },
  {
    id: "4",
    title: "Золотая Клетка",
    originalTitle: "Golden Cage",
    year: 2022,
    director: "Елена Свет",
    genres: ["Драма", "Биография"],
    synopsis: "История художницы, которая нашла свободу только внутри своей мастерской. Визуально роскошная биографическая драма.",
    posterColor: "from-twinpy-gold to-twinpy-neon",
    rating: 8.3,
  },
  {
    id: "5",
    title: "Сны Андроидов",
    originalTitle: "Android Dreams",
    year: 2024,
    director: "Кирилл Бинарный",
    genres: ["Фантастика", "Артхаус"],
    synopsis: "Что снится машине, которая научилась чувствовать? Философская фантастика о природе сознания.",
    posterColor: "from-twinpy-purple to-twinpy-turquoise",
    rating: 8.8,
  },
  {
    id: "6",
    title: "Последний Танец Теней",
    originalTitle: "Last Dance of Shadows",
    year: 2023,
    director: "Анна Тень",
    genres: ["Мюзикл", "Артхаус"],
    synopsis: "В мире, где у каждого есть тень-партнёр, одна девушка решает танцевать одна. Сюрреалистичный мюзикл о независимости.",
    posterColor: "from-twinpy-neon to-twinpy-purple",
    rating: 7.5,
  },
  {
    id: "7",
    title: "Бирюзовый Шторм",
    originalTitle: "Turquoise Storm",
    year: 2024,
    director: "Иван Ветер",
    genres: ["Приключения", "Драма"],
    synopsis: "Моряк отправляется в плавание, чтобы найти остров, которого не существует на картах. Эпическая история о вере и безумии.",
    posterColor: "from-twinpy-turquoise to-twinpy-gold",
    rating: 8.0,
  },
  {
    id: "8",
    title: "Шёпот Стен",
    originalTitle: "Whisper of Walls",
    year: 2022,
    director: "Ольга Камень",
    genres: ["Хоррор", "Артхаус"],
    synopsis: "Старый дом помнит всё. И он готов рассказать. Атмосферный хоррор без единого скримера — только звук и тишина.",
    posterColor: "from-twinpy-purple to-twinpy-neon",
    rating: 7.7,
  },
];